version: '3.8'

services:
  mongodb:
    image: mongo:latest
    env_file:
      - ./.env
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
    volumes:
      - ./data:/data/db

  client:
    build: ./client
    env_file:
      - ./.env
    volumes:
      - server_build:/app/build

  server:
    depends_on:
      - mongodb
      - client
    build: ./server
    env_file:
      - ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_ENV=mongodb
      - DB_PORT=27017
      - DB_DATABASE=cat-dog
    volumes:
      - server_build:/app/build
  
  nginx:
    image: nginx:latest
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  server_build: